server.port=8081

security.enabled=true

security.testing=false

spring.security.user.name=suser
spring.security.user.password=spassword

auth.users.admin.role=admin
auth.users.admin.password=password
auth.users.user3.role=user
auth.users.user3.password=test3
auth.users.user4.role=user
auth.users.user4.password=test4